# Copyright 2022 VMware
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")

#@ data.values.builder_image or assert.fail("missing builder_image")
---
apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: store
spec:
  sources:
    - image: gcr.io/paketo-buildpacks/go


---
apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: stack
spec:
  id: "io.buildpacks.stacks.bionic"
  buildImage:
    image: "paketobuildpacks/build:base-cnb"
  runImage:
    image: "paketobuildpacks/run:base-cnb"


---
apiVersion: kpack.io/v1alpha2
kind: ClusterBuilder
metadata:
  name: default
spec:
  serviceAccountRef:
    name: builder-service-account
    namespace: kpack
  tag: #@ data.values.builder_image
  stack:
    name: stack
    kind: ClusterStack
  store:
    name: store
    kind: ClusterStore
  order:
    - group:
        - id: paketo-buildpacks/go


---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: kpack
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: builder-service-account
  namespace: kpack
secrets:
  - name: registry-credentials
imagePullSecrets:
  - name: registry-credentials
